#ifndef _DATA_DEFINITION_H
#define _DATA_DEFINITION_H

#define DATA_FIRSTALTI "FIRSTALTI"
#define DATA_VELOCITY "VELOCITY"
#define DATA_ALTI     "ALTI"
#define DATA_ALTIFILTERED "ALTIFILTERED"
#define DATA_CALIBRATEDALTI "CALIBRATEDALTI"
#define DATA_TEMPERATURE "TEMPERATURE"

/***************************
 *     DEFAULT VALUES      *
 ***************************/


#define DEFAULT_VELOCITY 0
#define DEFAULT_FIRSTALTI 0
#define DEFAULT_ALTI 0
#define DEFAULT_ALTIFILTERED 0
#define DEFAULT_CALIBRATEDALTI 0
#define DEFAULT_TEMPERATURE 0

#endif //_DATA_DEFINITION_H

