#ifndef _DATASTATE_DEFINITION_H
#define _DATASTATE_DEFINITION_H

#define STATE_HAVENEWCLIMBRATEDATA "HAVENEWCLIMBRATEDATA"
#define STATE_HAVENEWCLIMBRATEDATABUZZER "HAVENEWCLIMBRATEDATABUZZER"
#define STATE_COMPTEURSTAERTFLYENABLE "COMPTEURSTARTFLYENABLE"
#define STATE_SPEEDAVALABLE "SPEEDAVALABLE"
#define STATE_GPSAVALABLE "GPSAVALABLE"

/***************************
 *     DEFAULT VALUES      *
 ***************************/

#define DEFAULT_HAVENEWCLIMBRATEDATA false
#define DEFAULT_HAVENEWCLIMBRATEDATABUZZER false
#define DEFAULT_COMPTEURSTARTFLYENABLE false
#define DEFAULT_SPEEDAVALABLE false
#define DEFAULT_GPSAVALABLE false


#endif //_DATASTATE_DEFINITION_H
