#pragma once

#define BTN_SHORT_A 1U
#define BTN_LONG_A 2U
#define BTN_SHORT_B 3U
#define BTN_LONG_B 4U
#define BTN_SHORT_C 5U
#define BTN_LONG_C 6U

#define WIFI_START_ASKED 7U
#define CALIBRATION_START_ASKED 8U
#define VARIO_START_ASKED 9U
#define HISTO_START_ASKED 10U

#define VOLUME_DOWN_ASKED 11U
#define VOLUME_UP_ASKED 12U
#define VOLUME_SAVE_ASKED 13U
#define VOLUME_TOGGLE_MUTE_ASKED 14U

#define AGL_INIT_ASKED 15U

#define VARIO_NEW_ALTI 16U
#define VARIO_NEW_VELOCITY 17U

#define GPS_FIXED 18U
#define GPS_LOST_FIXED 19U
#define GPS_NEW_POSITION 20U
#define GPS_NEW_ALTI_METERS 21U
#define GPS_NO_POSITION 22U
#define GPS_NEW_TIME 23U
#define GPS_NEW_SPEED 24U

#define FLIGHT_START 25U
#define FLIGHT_START_ASKED 26U

#define DEEP_SLEEP_ASKED 27U

#define HISTO_DISPLAY_ENTER 28U
