#pragma once

#define BTN_SHORT_A 1U
#define BTN_LONG_A 2U
#define BTN_SHORT_B 3U
#define BTN_LONG_B 4U
#define BTN_SHORT_C 5U
#define BTN_LONG_C 6U

#define WIFI_START_ASKED 7U
#define CALIBRATION_START_ASKED 8U

#define VOLUME_DOWN_ASKED 9U
#define VOLUME_UP_ASKED 10U
#define VOLUME_SAVE_ASKED 11U
#define VOLUME_TOGGLE_MUTE_ASKED 12U