#pragma once

#define BTN_SHORT_A 1U
#define BTN_LONG_A 2U
#define BTN_SHORT_B 3U
#define BTN_LONG_B 4U
#define BTN_SHORT_C 5U
#define BTN_LONG_C 6U

#define WIFI_START_ASKED 7U
#define CALIBRATION_START_ASKED 8U
#define VARIO_START_ASKED 9U
#define HISTO_START_ASKED 10U

#define VOLUME_DOWN_ASKED 11U
#define VOLUME_UP_ASKED 12U
#define VOLUME_TOGGLE_MUTE_ASKED 13U
#define VOLUME_EDIT_ENTER 14U
#define VOLUME_EDIT_EXIT 15U

#define AGL_INIT_ASKED 16U

#define VARIO_NEW_ALTI 17U
#define VARIO_NEW_VELOCITY 18U

#define GPS_FIXED 19U
#define GPS_LOST_FIXED 20U
#define GPS_NEW_POSITION 21U
#define GPS_NEW_ALTI_METERS 22U
#define GPS_NO_POSITION 23U
#define GPS_NEW_TIME 24U
#define GPS_NEW_SPEED 25U

#define FLIGHT_START 26U
#define FLIGHT_START_ASKED 27U

#define DEEP_SLEEP_ASKED 28U

#define HISTO_DISPLAY_ENTER 29U
