on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio pkg install --global --platform symlink://.
      - name: Build
        run: |
          sed -i 's/^\([^\/\/]*VARIOVERSION\)/\/\/\1/g' src/varioversion.h
          sed -i '/VARIOVERSION 154/s/^\/\///g' src/varioversion.h
          pio run --environment esp32dev 
          zip --junk-paths gnuVario-154 .pio/build/esp32dev/firmware.bin .pio/build/esp32dev/partitions.bin
          rm -rf .pio
          sed -i 's/^\([^\/\/]*VARIOVERSION\)/\/\/\1/g' src/varioversion.h
          sed -i '/VARIOVERSION 294/s/^\/\///g' src/varioversion.h
          pio run --environment esp32dev 
          zip --junk-paths gnuVario-294 .pio/build/esp32dev/firmware.bin .pio/build/esp32dev/partitions.bin
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset 154
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./gnuVario-154.zip
          asset_name: gnuVario-154.zip
          asset_content_type: application/zip
      - name: Upload Release Asset 294
        id: upload-release-asset-294
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./gnuVario-294.zip
          asset_name: gnuVario-294.zip
          asset_content_type: application/zip